{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "s3-to-wonderful-rag.fullname" . }}
  labels:
    {{- include "s3-to-wonderful-rag.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "s3-to-wonderful-rag.selectorLabels" . | nindent 6 }}
{{- end }}
