{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3-to-wonderful-rag.secretName" . }}
  labels:
    {{- include "s3-to-wonderful-rag.labels" . | nindent 4 }}
type: Opaque
stringData:
  aws_access_key_id: {{ .Values.secrets.awsAccessKeyId | quote }}
  aws_secret_access_key: {{ .Values.secrets.awsSecretAccessKey | quote }}
  azure_storage_key: {{ .Values.secrets.azureStorageKey | quote }}
  azure_storage_connection_string: {{ .Values.secrets.azureStorageConnectionString | quote }}
  wonderful_rag_id: {{ .Values.secrets.wonderfulRagId | quote }}
  wonderful_api_key: {{ .Values.secrets.wonderfulApiKey | quote }}
{{- end }}
