{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "s3-to-wonderful-rag.serviceAccountName" . }}
  labels:
    {{- include "s3-to-wonderful-rag.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
{{- end }}
