apiVersion: v1
kind: ConfigMap
metadata:
  name: wonderful-rag-config
  namespace: wonderful-rag
data:
  storage_provider: "s3"
  aws_region: "us-east-1"
  s3_bucket: "starsliderragdemo"
  s3_prefix: ""
  gcs_bucket: ""
  gcs_prefix: ""
  azure_storage_account: ""
  azure_storage_container: ""
  azure_storage_prefix: ""
  wonderful_tenant: "swiss-german"
  wonderful_env: "sb"
  sync_interval_seconds: "20"
  max_file_size_mb: "10"
